### ISSUE TITLE
kcl run command fails to resolve relative paths listed in a settings file

### ISSUE THREAD

**Issue by Fdall** [kcl-lang/cli#118]
### 1. Minimal reproduce step (Required)
Use the documentation example in https://www.kcl-lang.io/docs/user_docs/support/faq-cli#2-how-to-input-dynamic-options-how-to-get-dynamic-options-in-code

kcl_bug/file1.k
```
env = option("env-type")
deploy_topology = option("deploy-topology")
```

kcl_bug/settings.yaml
```
kcl_cli_configs:
  files:
    - file1.k
kcl_options:
  - key: env-type
    value: TEST
  - key: deploy-topology
    value:
      - cluster: my-cluster
        idc: my-idc
        replicas: 2
        workspace: my-workspace
        zone: my-zone
```

While inside the directory `kcl_bug`, the following command succeeds:

```
kcl run -Y settings.yaml
```

But if run using the absolute path of the settings file, from a directory that is not `kcl_bug` the command fails with:
```
Cannot find the kcl file, please check the file path file1.k
```

### 2. What did you expect to see? (Required)
The same setup works with any KCL release prior to the 0.9.X.
The relative path of files listed in the settings file should be resolved from the settings file and not from the user shell workdir.

### 3. What did you see instead (Required)

But if run using the absolute path of the settings file, from a directory that is not `kcl_bug` the command fails with:
```
Cannot find the kcl file, please check the file path file1.k
```
It seems that the files listed in the settings file are resolved from the workdir of the shell and not from the the settings file itself.
I could not find any CLI option to configure the 'root' folder from which the paths are resolved.

### 4. What is your KCL components version? (Required)

kcl version 0.9.1 -> not working
kcl version 0.8.9 -> working
